[project]
name = "deepagentsss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vivekanand-s-naik", email = "vivekanadsnaik.iet@srinivasuniversity.edu.in" }
]
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.7.23",
    "ipykernel>=7.3.0",
    "langchain>=1.4.4",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.6.0",
    "langchain-openrouter>=0.2.8",
    "python-dotenv>=1.2.3",
]

[project.scripts]
deepagentsss = "deepagentsss:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
